# Site settings
# in the templates available like {{ site.myvariable }}.
title: ET-Zhang
email: 13671256372@163.com
brand: Your Name
headline: ET-Zhang, web
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zhangyingjie.me" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: your.name@gmail.com
phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-83933844-1

